version: '3.8'

services:
  train-ticket-auto-query:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: train-ticket-auto-query
    ports:
      - "5001:5001"
    volumes:
      # 可选：挂载日志目录到宿主机
      - ./logs:/app/logs
    environment:
      # 这里可以覆盖默认环境变量
      # TS_BASE_URL: "http://你的服务器地址:端口"
      # TS_USERNAME: "你的用户名"
      # TS_PASSWORD: "你的密码"
      # TS_LOG_LEVEL: "DEBUG"  # 设置为DEBUG查看更详细日志
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s 